INSERT INTO STUDENT (ID, FULLNAME) VALUES (1, 'Amit Patel');
INSERT INTO STUDENT (ID, FULLNAME) VALUES (2, 'Rajan Patel');
INSERT INTO STUDENT (ID, FULLNAME) VALUES (3, 'Anil Patel');
INSERT INTO STUDENT (ID, FULLNAME) VALUES (4, 'Vikas Patel');
INSERT INTO STUDENT (ID, FULLNAME) VALUES (5, 'Ashok Patel');