package com.example.demo.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student Class - REST Operation.
 * 
 * @author VPillai
 *
 */
@Entity
@Table
@ApiModel(value = "Student", description = "Student Model Class")
public class Student {

	private int id;
	private String fullname;

	public Student() {
		super();
	}

	public Student(final int id, final String fullname) {
		super();
		this.id = id;
		this.fullname = fullname;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@ApiModelProperty(value = "Student ID is stored - Autogenerated", required = false)
	public int getId() {
		return id;
	}

	public void setId(final int id) {
		this.id = id;
	}

	@ApiModelProperty(value = "Student fullname is stored", required = true)
	public String getFullname() {
		return fullname;
	}

	public void setFullname(final String fullname) {
		this.fullname = fullname;
	}

	@Override
	public int hashCode() {
		int prime = 31;
		int result = 1;
		result = prime * result + id;
		return result;
	}

	@Override
	public boolean equals(final Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Student other = (Student) obj;
		if (id != other.id)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Student [id=" + id + ", fullname=" + fullname + "]";
	}

}
